openapi: 3.0.3
info:
  title: Magnets e-Commerce API
  description: API for managing products, orders, and user accounts for the Magnets e-Commerce platform.
  version: 1.0.0
servers:
  - url: http://localhost:4000
    description: Development server
  - url: https://api.igitest.pl
    description: Production server

paths:
  /products:
    get:
      summary: Get a list of products
      responses:
        '200':
          description: A JSON array of product objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Create a new product
      requestBody:
        description: Product object to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product created successfully

  /products/{id}:
    get:
      summary: Get a product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The product ID
      responses:
        '200':
          description: A product object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier for a product.
        name:
          type: string
          description: The name of the product.
        description:
          type: string
          description: A detailed description of the product.
        imgName:
          type: string
          description: The name of the image file associated with the product.
        createDate:
          type: string
          format: date-time
          description: The date and time when the product was created.
        editDate:
          type: string
          format: date-time
          description: The date and time when the product was last updated.
        idComments:
          type: array
          items:
            type: string
          description: An array of comment IDs associated with the product.
        price:
          type: object
          properties:
            defaultPrice:
              type: number
              format: float
              description: The default price of the product.
            discountPrice:
              type: number
              format: float
              description: The discounted price of the product, if applicable.
            editDate:
              type: string
              format: date-time
              description: The date and time when the price was last updated.
            lowestPrice30day:
              type: number
              format: float
              description: The lowest price of the product in the last 30 days, displayed if there's a discount
          required:
            - defaultPrice
            - editDate
          description: Price details including default and discounted prices, along with metadata.
        inStock:
          type: boolean
          description: Indicates whether the product is in stock.
      required:
        - id
        - name
        - price
        - createDate
        - editDate
